import { ApolloWrapper } from "./ApolloWrapper";
import { AuthProvider } from './auth';
import "./globals.css";


export const metadata = {
  title: "mo7tawa-dashboard",
  description: "Generated by mahmoud.code",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="ltr">
      <AuthProvider>
        <ApolloWrapper>
          <body>
            {children}
          </body>
        </ApolloWrapper>
      </AuthProvider>
    </html>
  );
}
